### ISSUE TITLE
code to have the json paths relative to a destination folder

### ISSUE THREAD

**Issue by minimit** [UltCombo/gulp-buster#15]
Here's the code to have the json paths relative to a destination folder:

	var dest = "public/";

	// Remove dest from manifest
	var bust_formatter = function(json){
	    var new_json = {};
	    for(var key in json) {
	        new_key = key.replace(dest, '');
	        new_json[new_key] = json[key];
	    }
	    return JSON.stringify(new_json);
	};

Use like this

	.pipe(bust({formatter:bust_formatter}))

**Comment by jmagnusson** [comment]
@UltCombo It would be nice to have the relative root as an option. Is that something to add perhaps? Using `replace` on the already generated filepath feels kind of dirty.

**Comment by UltCombo** [comment]
@jmagnusson true, looking back now my recipe above does not look very good.

I don't want to bloat the API, but I guess this is a common enough use case and it is pretty simple to implement (calling `path.relative()` should be enough).

I'm a little short on free time now though. I'm willing to take PRs.

**Comment by jmagnusson** [comment]
Same here. I'll look into it if I get the time ;-)
