### ISSUE TITLE
Can't get it to rename the file it's fingerprinting.

### ISSUE THREAD

**Issue by jakecleary** [UltCombo/gulp-buster#18]
I'm using `gulp-buster`, and love how simple it it to use. However, I'm struggling to get it to output the compiled file with the fingerprinted name.

**Heres the task I'm using:**

```js
gulp.task('styles', function() {
    gulp.src(paths.assets.styles.files)
        .pipe(sass({sourceComments: 'normal'}))
        .pipe(autoprefix(settings.autoprefix.versions))
        .pipe(gulp.dest(paths.public.styles))
        .pipe(bust())
        .pipe(gulp.dest(paths.hash.dir));
});
```

It's generating the manifest file correctly, but outputting `main.css` without a hash in it's name.

Is this intended? Do I need to write my own implementation?

Let me know if I'm being unclear.

**Comment by UltCombo** [comment]
Hey there `=]`

Yes, right now gulp-buster only generates a file containing the hashes. Looks like your use case is covered by [gulp-rev](https://www.npmjs.com/package/gulp-rev) (and you may also need [gulp-rev-replace](https://www.npmjs.com/package/gulp-rev-replace)).

**Comment by jakecleary** [comment]
Yeah I wasn't able to get `gulp-rev` working as I intended. It doesn't seem to delete previously created files, so I ended up with my `styles` directory being full of `main-xxxxxxxx.css` files...

I need to spend some more time using your plugin I think. I almost got it to rename the file every time with a bit of code in my `gulpfile.js`.

Thanks for putting `gulp-buster` together!

**Comment by UltCombo** [comment]
> so I ended up with my styles directory being full of main-xxxxxxxx.css files...

I guess you're supposed to use [`rimraf`](https://www.npmjs.com/package/rimraf)/[`del`](https://www.npmjs.com/package/del) to delete all files from your `gulp.dest()` dir before each build. This probably won't play well if you're using an incremental build strategy though.

I personally tend to add the hash to the files' query strings (e.g. `href="unicorn.css"` -> `href="unicorn.css?md5_hash"`), this way you don't have to rename the files and incremental builds work perfectly fine (each built file overwrites the previous build's, as the files still have the same name).

> I need to spend some more time using your plugin I think. I almost got it to rename the file every time with a bit of code in my gulpfile.js.
>
> Thanks for putting gulp-buster together!

No problem. `;)` Feel free to send a recipe later if you figure out something that may be useful for other users as well.

**Comment by BenBish** [comment]
@UltCombo Please can you give an example of how you do this?

> I personally tend to add the hash to the files' query strings (e.g. href="unicorn.css" -> href="unicorn.css?md5_hash")...

**Comment by UltCombo** [comment]
@BenBish I usually do that at runtime, see [implementation examples](https://github.com/UltCombo/gulp-buster/blob/master/IMPLEMENTATION-EXAMPLE.md) and existing [implementations](https://github.com/UltCombo/gulp-buster/blob/master/IMPLEMENTATIONS.md).

**Comment by UltCombo** [comment]
It might be viable to do it at build time (ala gulp-rev-replace/gulp-useref) but I didn't really like their pipes logic. I'm still planning this for the future though.
