### ISSUE TITLE
Add hash to filename

### ISSUE THREAD

**Issue by KaoruDev** [UltCombo/gulp-buster#21]
Is there an easy way to rename the file that is being hashed by appending the hash to the file?

i.e. start with: `./src/main.css` and then get back `./build/main_<hash>.css` where `<hash>` is the md5 hash of the file?

**Comment by UltCombo** [comment]
gulp-buster only generates a manifest file, which is suitable for dynamically injecting the hash in the assets' query strings.

I believe you are looking for statically versioned files, if so take a look at [gulp-rev](https://github.com/sindresorhus/gulp-rev) + [gulp-rev-replace](https://github.com/jamesknelson/gulp-rev-replace).

**Comment by KaoruDev** [comment]
looks like i am thanks! 💯
