### ISSUE TITLE
Hash not updating?

### ISSUE THREAD

**Issue by sta1r** [UltCombo/gulp-buster#23]
Each time I pipe my assets into `bust()` it generates the same cache id hash for the corresponding file. Shouldn't it generate a new unique hash every time?

**Comment by UltCombo** [comment]
The hashes are based on the file contents. If the file content changes, the hash changes. If the file content remains the same, you usually want the hash to remain the same so your application can reuse any browser/proxy cache that is still valid.

The user can pass a custom hashing function to [`options.algo`](https://github.com/UltCombo/gulp-buster#parameters), so it shouldn't be hard to achieve a "new unique hash every time" if that's what you actually want, but that pretty much defeats the purpose of this plugin and may be even easier to achieve without gulp at all.
